version: '3.12'
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
      - --port ${REDIS_PORT}
    env_file:
      - .env
    restart: on-failure
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  bot:
    build: .
    command: sh -c "python -m run"
    env_file:
      - .env
    restart: always
    volumes:
      - migrations:/app/bot/database/migrations/versions
    depends_on:
      - db
      - redis

volumes:
  migrations:
  pgdata: